from learn import *
import string
if __name__ == '__main__':
    word_list = [    
#    word(r'b{\ae}ts',{'ROOT':'BAT','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'b{\ae}t',{'ROOT':'BAT','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'c{\ae}ts',{'ROOT':'CAT','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'toU',{'ROOT':'TOE','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'toUz',{'ROOT':'TOE','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'fIS',{'ROOT':'FISH','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'fIS9z',{'ROOT':'FISH','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'dAg',{'ROOT':'DOG','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'dAgz',{'ROOT':'DOG','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'm{\ae}n',{'ROOT':'MAN','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'men',{'ROOT':'MAN','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'wUm{\ae}n',{'ROOT':'WOMAN','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'wUmen',{'ROOT':'WOMAN','OTHER':[('NUMBER',frozenset(['PL']))]}),
#    word(r'fut',{'ROOT':'FOOT','OTHER':[('NUMBER',frozenset(['SG']))]}),
#    word(r'fit',{'ROOT':'FOOT','OTHER':[('NUMBER',frozenset(['PL']))]}),
    word(r'fIS',{'ROOT':'FISH','OTHER':[('TAM',frozenset(['PRESENT']))]}),
    word(r'fISIN',{'ROOT':'FISH','OTHER':[('TAM',frozenset(['PRESENT PARTICIPLE']))]}),
    word(r'fISt',{'ROOT':'FISH','OTHER':[('TAM',frozenset(['PAST']))]}),
    word(r'plej',{'ROOT':'PLAY','OTHER':[('TAM',frozenset(['PRESENT']))]}),
    word(r'plejIN',{'ROOT':'PLAY','OTHER':[('TAM',frozenset(['PRESENT PARTICIPLE']))]}),
    word(r'plejd',{'ROOT':'PLAY','OTHER':[('TAM',frozenset(['PAST']))]}),
    word(r'wOk',{'ROOT':'WALK','OTHER':[('TAM',frozenset(['PRESENT']))]}),
    word(r'wOkt',{'ROOT':'WALK','OTHER':[('TAM',frozenset(['PAST']))]}),
    word(r'wOkIN',{'ROOT':'WALK','OTHER':[('TAM',frozenset(['PRESENT PARTICIPLE']))]}),
    word(r'brIN',{'ROOT':'BRING','OTHER':[('TAM',frozenset(['PRESENT']))]}),
    word(r'brat',{'ROOT':'BRING','OTHER':[('TAM',frozenset(['PAST']))]}),
    word(r'brININ',{'ROOT':'BRING','OTHER':[('TAM',frozenset(['PRESENT PARTICIPLE']))]}),
    word(r'rIN',{'ROOT':'RING','OTHER':[('TAM',frozenset(['PRESENT']))]}),
    word(r'r{\ae}N',{'ROOT':'RING','OTHER':[('TAM',frozenset(['PAST']))]}),
    word(r'rININ',{'ROOT':'RING','OTHER':[('TAM',frozenset(['PRESENT PARTICIPLE']))]}),
    word(r'sIN',{'ROOT':'SING','OTHER':[('TAM',frozenset(['PRESENT']))]}),
    word(r's{\ae}N',{'ROOT':'SING','OTHER':[('TAM',frozenset(['PAST']))]}),
    word(r'sININ',{'ROOT':'SING','OTHER':[('TAM',frozenset(['PRESENT PARTICIPLE']))]}),
    ]
    settings = Settings(3, 3, 5, 3, 2, 1, 2, 5)
    learnVocab(word_list,settings,iterate=True)
